% remove background for all cores in the study

corePath = {'/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R8C2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R4C5/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R6C9/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S2R3C3/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S2R9C5/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores3/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point4/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point5/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point6/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point7/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point8/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point9/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point10/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point11/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point12/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point13/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point14/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point15/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point16/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point17/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point18/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point19/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point4/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point5/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point6/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point7/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point8/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point9/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point10/' ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML1_FOV1/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML1_FOV2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML2_FOV1/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML2_FOV2/Point1/'};

coreNum= length(corePath);

cleanDataPath = '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/CleanData';

% load noise threshold file
massDSNew = MibiReadMassData(['/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/TNBC_panel_170505_with_bg.csv']);

% remove noise and replot
for i=7
    i
    load([corePath{i},'dataDeNoise.mat']);
    % get new IntNormD for data without bg
    %for j=7:length(massDS)-2
    massDS = massDSNew;
    for j=7:length(massDS)-2
        IntNormD{j}=MibiGetIntNormDist(countsNoBg(:,:,j),countsNoBg(:,:,j),25,2,25);
    end
    countsNoNoise = MibiFilterAllByNN(countsNoBg,IntNormD,massDS.NoiseT);
    save ([corePath{i},'dataDeNoise.mat'],'totalIonFiltSum','countsAllSFiltCRSum','countsNoNoise','massDS','IntNormD','pointNumber','countsNoBg');
    mkdir([cleanDataPath,'/Point',num2str(i)]);
    save([cleanDataPath,'/Point',num2str(i),'/dataDeNoiseCohort.mat'],'countsNoNoise');
end