% remove background for all cores in the study

corePath = {'/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R8C2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R4C5/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S1R6C9/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S2R3C3/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA460-S2R9C5/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_MultipleCores3/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point4/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point5/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point6/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point7/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point8/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point9/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point10/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point11/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point12/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point13/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point14/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point15/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point16/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point17/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point18/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-459_multipleCores2/Point19/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point4/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point5/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point6/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point7/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point8/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point9/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/TA-460_secondstaining2/Point10/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point2/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/BreastNMLControls/Point3/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML1_FOV1/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML1_FOV2/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML2_FOV1/Point1/', ...
    '/Users/lkeren/Box Sync/Leeat_Share/Data/MIBIData/171016_BreastNormals/BreastNML2_FOV2/Point1/'};


coreNum= length(corePath);

% % params for filtering cd45 by gold
% bgChannel = 'Au';
% targetChannels = {'CD45'};
% cap = 200;
% t=0.3;
% removeVal = 2;
% gausRad=3;
% % parameters for last 4 normals done with the new MIBI
% % t=0.07;

% % don't use. I filter by gold
% % params for filtering cd45 by si 
% bgChannel = 'Si';
% targetChannels = {'CD45'};
% cap = 20;
% t=0.1;
% removeVal = 2;
% gausRad=3;

% params for filtering cd16 by nuclear channel
bgChannel = 'dsDNA';
targetChannels = {'CD16'};
cap = 20;
t=0.2;
removeVal = 2;
gausRad=3;
% parameters for last 4 normals done with the new MIBI
t=0.02;

% params for filtering cd209 by si
% bgChannel = 'Si';
% targetChannels = {'CD209'};
% cap = 20;
% t=0.1;
% removeVal = 2;
% gausRad=3;

for i=45:48
    i
    load([corePath{i},'dataDeNoise.mat']);
    [~,bgChannelInd] = ismember(bgChannel,massDS.Label);
    mask = MibiGetMask(countsAllSFiltCRSum(:,:,bgChannelInd),cap,t,gausRad);
    for j=1:length(targetChannels)
        [~,targetChannelInd] = ismember(targetChannels{j},massDS.Label);
        countsNoBg(:,:,targetChannelInd) = MibiRemoveBackgroundByMaskSingleChannel(countsAllSFiltCRSum(:,:,targetChannelInd),mask,removeVal);
    end
    save ([corePath{i},'dataDeNoise.mat'],'totalIonFiltSum','countsAllSFiltCRSum','countsNoNoise','massDS','IntNormD','pointNumber','countsNoBg');
    close all;
end